_target_: watchmal.model.contrastive_resnet.vmdls_classif.VMDLS_Classifier
class_num : 4
enc_type: "resnet18"
latent_dim : 32
channels : 19
model_file_path : "/home/Antoine.m/WatChMaL/outputs/2023-05-13/04-53-26/outputs/GMM_VAE_ContrastiveBEST.pth"