epochs: 60

report_interval: 500
val_interval: 500
num_val_batches: 32
reconstruction_weight : 25
noise_gen_weight : 6

checkpointing: False
data_loaders:
  train:
    split_key: train_idxs
    batch_size: 1024
    num_workers: 2
    transforms: 
      - pad

     
      
  validation:
    split_key: val_idxs
    batch_size: 1024
    num_workers: 2
    transforms:
      - pad

    

  
