epochs: 20

report_interval: 16000
val_interval: 16000
num_val_batches: 32

checkpointing: True

data_loaders:
  train:
    split_key: train_idxs
    batch_size: 64
    is_batch : True
    num_workers: 4
    transforms:
      - x_flip
      - y_flip
      - z_flip
  validation:
    split_key: val_idxs
    batch_size: 64
    is_batch : True
    num_workers: 4