epochs: 1

report_interval: 100
val_interval: 100
num_val_batches: 32

checkpointing: False
extract_embedding : 1
data_loaders:
  train:
    split_key: train_idxs
    batch_size: 1024
    num_workers: 2
    transforms:
      - horizontal_flip
      - vertical_flip
      - front_back_reflection
  validation:
    split_key: val_idxs
    batch_size: 1024
    num_workers: 2
