gpu_list:
    - 0
seed: null
dump_path: './outputs/'
defaults:
    - data: iwcd_short
    - data/dataset: iwcd_cnn_short
    - model: vmdls
    - engine: contrastive
    - tasks/restore_state: restore_state_vmdls
    - tasks/evaluate: test_vmdls
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
    - _self_