gpu_list:
    - 5
seed: null
dump_path: './outputs/'
defaults:
    - data: iwcd_short
    - data/dataset: iwcd_cnn_short
    - model: vmdls
    - engine: contrastive
    - tasks/train: train_vmdls
    - optimizers@tasks.train.optimizers: adam
    - schedulers@tasks.train.schedulers : step
    - sampler@tasks.train.data_loaders.train.sampler: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler: subset_random
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test_vmdls
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
    - _self_